### ISSUE TITLE
meet an error when completely follow the instructions

### ISSUE THREAD

**Issue by kyle5358** [rtaori/Black-Box-Audio#21]
hello rtaoi!
I run you code on ubuntu, but I have this error:

Traceback (most recent call last):
  File "run_audio_attack.py", line 256, in <module>
    g = Genetic(inp_wav_file, out_wav_file, target)
  File "run_audio_attack.py", line 126, in __init__
    self.funcs = self.setup_graph(self.pop, np.array([toks.index(x) for x in target_phrase]))
  File "run_audio_attack.py", line 148, in setup_graph
    target = ctc_label_dense_to_sparse(arg1_dense, arg2_dense, len_batch)
  File "DeepSpeech/util/text.py", line 173, in ctc_label_dense_to_sparse
    dense_mask = tf.scan(range_less_than, label_lengths, initializer=init, parallel_iterations=1)
  File "/home/kyle/anaconda3/envs/adversarialaudio/lib/python3.6/site-packages/tensorflow_core/python/ops/functional_ops.py", line 508, in scan
    maximum_iterations=n)
  File "/home/kyle/anaconda3/envs/adversarialaudio/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2753, in while_loop
    return_same_structure)
  File "/home/kyle/anaconda3/envs/adversarialaudio/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2245, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/kyle/anaconda3/envs/adversarialaudio/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2211, in _BuildLoop
    next_vars.append(_AddNextAndBackEdge(m, v))
  File "/home/kyle/anaconda3/envs/adversarialaudio/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 601, in _AddNextAndBackEdge
    _EnforceShapeInvariant(m, v)
  File "/home/kyle/anaconda3/envs/adversarialaudio/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 586, in _EnforceShapeInvariant
    "less-specific shape." % (input_t.name, input_t.shape, n_shape))
ValueError: Input tensor 'ExpandDims:0' enters the loop with shape (1, 11), but has shape (1, ?) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.

I am a freshman in this area and in audio_adversarial_attack, haven't you met this error?

**Comment by rtaori** [comment]
Hello @Yao-kai,

Can you confirm you have installed the correct version of packages from `requirements.txt` and have downloaded the correct version of DeepSpeech via `git clone -b 'v0.1.1' --single-branch --depth 1 https://github.com/mozilla/DeepSpeech.git` ?
