### ISSUE TITLE
Denpendency problem

### ISSUE THREAD

**Issue by ruby11dog** [rtaori/Black-Box-Audio#8]
**When i type "python3 run_audio_attack.py sample_input.wav "hello world""** 

Traceback (most recent call last):
  File "run_audio_attack.py", line 37, in <module>
    import DeepSpeech
  File "DeepSpeech/DeepSpeech.py", line 21, in <module>
    from tensorflow.contrib.lite.python import tflite_convert
ModuleNotFoundError: No module named 'tensorflow.contrib.lite'

My environment is : tensorflow-gpu==1.14.0 DeepSpeech:0.4.0
Can you tell me the exact version of tensorflow and DeepSpeech which is used in this code?
Thanks!!

**Comment by rtaori** [comment]
Hi,
tensorflow-gpu==1.14.0  is correct. Can you try checking out this version of DeepSpeech?:

`cd DeepSpeech`
`git checkout 033ee0f4c2b460b09e3de8725b5b8b2cc93717ec`

**Comment by ruby11dog** [comment]
Thanks for your reply,
now i check out this version 033ee0f4c2b460b09e3de8725b5b8b2cc93717ec , and here is another problem:

1.type python3 run_audio_attack.py input_file.wav "target phrase":
Traceback (most recent call last):
  File "make_checkpoint.py", line 16, in <module>
    from util.text import ctc_label_dense_to_sparse
ImportError: cannot import name 'ctc_label_dense_to_sparse'

2.type python3 run_audio_attack.py sample_input.wav "hello world":
Traceback (most recent call last):
  File "run_audio_attack.py", line 41, in <module>
    DeepSpeech.TrainingCoordinator.__init__ = lambda x: None
AttributeError: module 'DeepSpeech' has no attribute 'TrainingCoordinator'

I'm confused now, can you help me about that?
Thanks!

**Comment by rtaori** [comment]
Hi,
Could you try commit `e3bda9e964239c152db98f95cca26dca2af0d7ef`? Let me know if that works for you and I can update the repo
Thanks

**Comment by ruby11dog** [comment]
It still does't work, in e3bda9e964239c152db98f95cca26dca2af0d7ef,

 type python3 make_checkpoint.py :

Traceback (most recent call last):
  File "make_checkpoint.py", line 23, in <module>
    import DeepSpeech as DeepSpeech
  File "DeepSpeech/DeepSpeech.py", line 21, in <module>
    from tensorflow.contrib.lite.python import tflite_convert
ModuleNotFoundError: No module named 'tensorflow.contrib.lite'

type python3 run_audio_attack.py sample_input.wav "hello world":

Traceback (most recent call last):
  File "run_audio_attack.py", line 37, in <module>
    import DeepSpeech
  File "DeepSpeech/DeepSpeech.py", line 21, in <module>
    from tensorflow.contrib.lite.python import tflite_convert
ModuleNotFoundError: No module named 'tensorflow.contrib.lite'

I try to modify "tensorflow.contrib.lite.python" to "tensorflow.lite.python", and try to type "python3 make_checkpoint.py"but don't work:

Traceback (most recent call last):
  File "make_checkpoint.py", line 45, in <module>
    mfcc = audiofile_to_input_vector("sample.wav", 26, 9)
  File "DeepSpeech/util/audio.py", line 15, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/wavfile.py", line 264, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'sample.wav'


Maybe the version of tensorflow is wrong?

**Comment by rtaori** [comment]
Pushed a fix for that last error you're having. Try again?

**Comment by ruby11dog** [comment]
Thanks for that, but now i have this problem when make_checkpoint:

`Traceback (most recent call last):
  File "make_checkpoint.py", line 49, in <module>
    tf.app.flags.FLAGS.alphabet_config_path = "DeepSpeech/data/alphabet.txt"
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 499, in __setattr__
    return self._set_unknown_flag(name, value)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 375, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'alphabet_config_path'`

**Comment by rtaori** [comment]
Closing this issue as it is being tracked on #7

**Comment by rtaori** [comment]
Hi @ruby11dog,

I have updated the installation instructions with much more detail in the [README](https://github.com/rtaori/Black-Box-Audio#installation).
Please follow the steps there and open another issue if you still have any problems.
